import yaml

from ado_migrate.client import InMemoryFakeAdoClient
from ado_migrate.identity_map_gen import collect_identities, parse_args, render_identity_map


def test_parse_args_reads_required_flags():
    args = parse_args(
        [
            "--org", "https://dev.azure.com/myorg",
            "--pat-env", "ADO_PAT",
            "--project", "MyProject",
        ]
    )

    assert args.org == "https://dev.azure.com/myorg"
    assert args.pat_env == "ADO_PAT"
    assert args.project == "MyProject"
    assert args.output == "identity.yaml"


def test_parse_args_accepts_custom_output_path():
    args = parse_args(
        [
            "--org", "https://dev.azure.com/myorg",
            "--pat-env", "ADO_PAT",
            "--project", "MyProject",
            "--output", "custom.yaml",
        ]
    )

    assert args.output == "custom.yaml"


def test_collect_identities_returns_sorted_unique_project_users():
    client = InMemoryFakeAdoClient(dry_run=False)
    client.seed_project_users(
        "SourceProject",
        ["bob@source.com", "alice@source.com", "alice@source.com"],
    )

    identities = collect_identities(client, "SourceProject")

    assert identities == ["alice@source.com", "bob@source.com"]


def test_collect_identities_returns_empty_list_when_no_project_users():
    client = InMemoryFakeAdoClient(dry_run=False)

    assert collect_identities(client, "SourceProject") == []


def test_render_identity_map_defaults_each_identity_to_itself():
    content = render_identity_map(["alice@source.com", "bob@source.com"])
    parsed = yaml.safe_load(content)

    assert parsed == {
        "mappings": {
            "alice@source.com": "alice@source.com",
            "bob@source.com": "bob@source.com",
        }
    }
    assert content.startswith("# Generated by generate-identity-map.")


def test_render_identity_map_handles_no_identities():
    content = render_identity_map([])
    parsed = yaml.safe_load(content)

    assert parsed == {"mappings": {}}
