"""generate-identity-map: scan a source project's work items for AssignedTo
identities and emit a starter identity.yaml, each identity defaulted to
itself as the destination value.

Network calls (`main`) are deliberately excluded from the automated test
suite, consistent with this codebase's convention for real-client entry
points (see seed_ado.py). `parse_args`, `collect_identities`, and
`render_identity_map` are pure and unit tested.
"""

import argparse
import logging
import os
import sys
from argparse import Namespace

import yaml

from ado_migrate.client import AdoClient
from ado_migrate.real_client import RealAdoClient

logger = logging.getLogger(__name__)

_HEADER = (
    "# Generated by generate-identity-map.\n"
    "# Each source identity below defaults to itself as the destination\n"
    "# identity. Replace the right-hand side with the matching identity in\n"
    "# the destination org before running `migrate`.\n"
)


def parse_args(argv: list[str]) -> Namespace:
    parser = argparse.ArgumentParser(prog="generate-identity-map")
    parser.add_argument("--org", required=True)
    parser.add_argument("--pat-env", required=True)
    parser.add_argument("--project", required=True)
    parser.add_argument("--output", default="identity.yaml")
    return parser.parse_args(argv)


def collect_identities(client: AdoClient, project: str) -> list[str]:
    identities: set[str] = set()
    for work_item in client.list_work_items(project):
        for revision in work_item.revisions:
            assigned_to = revision.get("AssignedTo")
            if assigned_to:
                identities.add(assigned_to)
    return sorted(identities)


def render_identity_map(identities: list[str]) -> str:
    mappings = {identity: identity for identity in identities}
    body = yaml.safe_dump({"mappings": mappings}, sort_keys=True, default_flow_style=False)
    return _HEADER + body


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    args = parse_args(argv if argv is not None else sys.argv[1:])

    pat = os.environ.get(args.pat_env)
    if pat is None:
        print(f"Environment variable '{args.pat_env}' is not set", file=sys.stderr)
        return 1

    client = RealAdoClient(args.org, pat, dry_run=True)
    identities = collect_identities(client, args.project)

    with open(args.output, "w") as f:
        f.write(render_identity_map(identities))

    logger.info(
        "Found %d distinct identity(ies). Wrote %s — fill in destination "
        "identities before running migrate.",
        len(identities),
        args.output,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
